import { articleType } from "../dto/dto";

export default function getArticles(): Array<articleType> {
  const articles: Array<articleType> = [
    {
      title:
        "Importance of recycling education: a curriculum development at WSU",
      desc: "The use of recyclable materials has been continuously increasing worldwide due to economic, environmental, and technological developments. Not reusing recyclable materials means that they will be degraded or corroded, and then completely destroyed by nature, thus representing a waste of resources and much environmental damage. To increase both academic and public awareness of recycling, the authors have developed a three-credit-hour recycling course entitled “Recycling of Engineering Materials” at the College of Engineering at Wichita State University, which was taught in spring 2008 and 2010. The lectures focused on basic characterization and separation techniques of recyclable materials, recycled products, environmental concerns, and potential commercial applications. Throughout the lectures, students were expected to gain an understanding of recycling concepts, processing techniques, recent progress on recycling, as well as health issues relating to toxic and hazardous materials and their handling procedures. The survey results confirmed that the course is well established and understood by the undergraduate and graduate students.",
      time: 10,
      content: `Recycling has always been one of the first strategies that come to mind when individuals and institutions want to perform a positive behaviour towards the environment, however the necessary determination and stability could not be achieved apart from a few examples when it comes to certain practices. Except for the activities of certain private institutions and foundations, there are scarcely any comprehensive examples of the recycling education within the curriculum of the institutions affiliated to Ministry of Education or universities (Ugulu et al. 2014). \n When the place of the recycling education in the international area is examined, a multi-dimensional development stands out in this area in parallel with the environmental education. While most of the practices in our country still cannot go beyond a few definitions about the recycling education, international practices consist of complicated curriculum programs created in a way that they include high and higher education starting from preschool education.`,
    },
    {
      title: "A study on matter cycle",
      desc: "The objective of this study is to analyze and determine whether developed recycling education program would lead to a positive change in the conceptual understanding of ecological concepts associated with matter cycles by high school students. The research was conducted on 68 high school 10th grade students (47 female and 21 male students).",
      time: 3,
      content: `As a result of the study, it was observed that high school students have many misconceptions towards basic ecological concepts. In their study, Boyes and Stanisstrect (1999) put forth that a great majority of the students developed the thought that the world heats up as one of the negative consequences of global warming, and consequently they developed such a misconception as “the desertification areas in the world will increase as global warming increases”. When the answers given to EECUT WC question by the students in our study are examined, it is observed that a great majority of the students developed such a misconception that global warming will reduce the water sources. Thus, this misconception overlaps with the misconception indicated in the study of Boyes and Stanisstrect (1999). Munson (1994) conducted researches on how the students cope with misconceptions about ecology by examining the subject change of concept after reviewing the researches carried out on the constructivist learning hypothesis. \n In his study, Munson (1994) determined that the studies carried out on science teaching in the framework of the constructivist approach are related to the fact that “the learning of the new concepts by the students are related to their previous knowledge (Carey 1985; Driver et al. 1985; Osborne and Freyberg 1985).” Thus, he mentioned the importance of misconceptions in the structuring of the new of information. Starting from this theoretical substructure and assessing the importance of misconceptions in environmental education, Munson (1994) summarized the main ecological concepts and the misconceptions related to these concepts. As a result of the study, it was determined that the misconceptions on this subject are quite important in terms of environmental education and instructors.`,
    },
    {
      title: "Recycling in Schools: How Can We Reduce Waste?",
      desc: "According to Recycle Now, the average primary school produces 45kg of waste per pupil each academic year. Furthermore, it’s believed that up to 78% of this waste could be easily recycled or composted. If your school can reduce the amount of waste it produces and implement recycling, not only will your actions have an environmental impact, but it will also benefit your pupils in the long run.",
      time: 5,
      content:
        "By educating pupils about the importance of recycling, we are inspiring them to think about how their personal actions affect the planet and their future environment. Learning about recycling in schools means that children are more likely to adopt it as a habit, helping to make them conscientious adults. This encourages students to implement their recycling tactics in their everyday life, helping to tackle the waste they produce at home. \n Recycling can really make a difference to our natural environment. It prevents materials from being sent to landfill and in turn, helps to cut down on the energy and greenhouse gases produced when new materials are created. These activities have a significant negative impact on the environment, contributing to climate change. You can encourage children to do their part by following three simple steps: reduce, reuse, and recycle. Recycling 1 ton of printing paper, for example, can help to save 24 trees from being cut down.",
    },
    {
      title: "How Can Can Education Improve The Recycling Behaviors",
      desc: "By completing an investigation on how can education improve the recycling behaviors and attitudes of middle school students, I am hoping to determine how to best influence and improve the recycling practices of middle school students.",
      time: 6,
      content:
        "I want my students to see how their actions and decisions can influence something much larger. To do this, I will introduce them to their carbon footprint. We will dissect what makes the footprints larger or smaller, extrapolate the global implications of our carbon footprints and our current population, and evaluate and develop changes they can make to lessen their footprints. \n By educating students on where the things in our daily lives come from, what goes into making them, what happens when we throw them away, and how these small pieces of knowledge and choices affect our carbon footprints, students can start to extrapolate how around the world people have a great power to  10 influence larger outcomes. With all of this being said, change starts small. Recycling is something that almost everyone is able to do, and when done correctly, it can start to be the small change that will make the big difference. In the following section I will be highlighting some educational strategies that have been used to influence changes in actions through a review of literature from other publications. \n There will also be current practices in schools that are showing success. Chapter three will discuss the strategies I have chosen to implement and the methods in which I did so. Next, will be my results and findings, followed by conclusions that I was able to draw from the data I collected. ",
    },
  ];

  return articles;
}
